name: build

on: [push]

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install
      env:
        GITHUB_TOKEN: ${{secrets.GH_PACKAGE_REGISTRY_TOKEN}}
      run: |
        echo "@npezza93:registry=https://npm.pkg.github.com/" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
        yarn --link-duplicates --pure-lockfile --ignore-engines
    - name: Setup signing
      env:
        CSC_LINK: ${{ secrets.CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      run: |
        export CERTIFICATE_P12=cert.p12;
        echo $CSC_LINK | base64 --decode > $CERTIFICATE_P12;
        export KEYCHAIN=build.keychain;
        security create-keychain -p archipelago $KEYCHAIN;
        security default-keychain -s $KEYCHAIN;
        security unlock-keychain -p archipelago $KEYCHAIN;
        security import $CERTIFICATE_P12 -k $KEYCHAIN -P $CSC_KEY_PASSWORD -T /usr/bin/codesign 2>&1 >/dev/null;
        rm $CERTIFICATE_P12;
        security set-key-partition-list -S apple-tool:,apple: -s -k travis $KEYCHAIN
        security find-identity -v -p codesigning
    - name: Build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      run: |
      # yarn electron-packager . Archipelago --platform=darwin --arch=arm64 --icon=build/icon.icns --overwrite --out=dist
