name: build

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install
      env:
        GITHUB_TOKEN: ${{secrets.GH_PACKAGE_REGISTRY_TOKEN}}
      run: |
        echo "@npezza93:registry=https://npm.pkg.github.com/" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
        yarn --link-duplicates --pure-lockfile --ignore-engines
    - name: Setup signing
      env:
        CSC_LINK: ${{ secrets.CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      run: |
        export CERTIFICATE_P12=cert.p12;
        echo $CSC_LINK | base64 --decode > $CERTIFICATE_P12;
        security import $CERTIFICATE_P12 -P $CSC_KEY_PASSWORD -T /usr/bin/codesign 2>&1 >/dev/null;
        rm $CERTIFICATE_P12;
    - name: Get the release version from the tag
      run: |
        # Apparently, this is the right way to get a tag name. Really?
        #
        # See: https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32167/highlight/true#M1027
        echo "ARCHIPELAGO_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "version is: ${GITHUB_REF#refs/tags/}"
    - name: Build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      run: yarn dist
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        draft: true
        tag_name: ${{ env.ARCHIPELAGO_VERSION }}
        token: ${{ env.GITHUB_TOKEN }}
        files: |
          dist/Archipelago-darwin-x64.zip
          dist/Archipelago-darwin-arm64.zip
