name: build

on: [push]

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install
      env:
        GITHUB_TOKEN: ${{secrets.GH_PACKAGE_REGISTRY_TOKEN}}
      run: |
        echo "@npezza93:registry=https://npm.pkg.github.com/" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
        yarn --link-duplicates --pure-lockfile --ignore-engines
    - name: Set up secret file
      env:
        CSC_LINK: ${{ secrets.CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      run: |
        echo $CSC_LINK >> secrets.txt
        echo $CSC_KEY_PASSWORD >> secrets.txt
    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
    - name: Build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        CSC_LINK: ${{ secrets.CSC_LINK }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      run: |
        # yarn electron-packager . Archipelago --platform=darwin --arch=arm64 --icon=build/icon.icns --overwrite --out=dist
