name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Lint
      run: |
        yarn --link-duplicates --pure-lockfile --ignore-engines
        yarn lint
