name: test

on: [push]

jobs:
  test:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Setup npmrc
      env:
        GITHUB_TOKEN: ${{secrets.GH_PACKAGE_REGISTRY_TOKEN}}
      run: |
        echo "@npezza93:registry=https://npm.pkg.github.com/" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - name: Test
      run: yarn test
