name: mac_build

on: [push]

jobs:
  build:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build
      run: |
        yarn --link-duplicates --pure-lockfile --ignore-engines
        yarn test
