name: mac

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install
      run: yarn --link-duplicates --pure-lockfile --ignore-engines
    - name: Test
      run: yarn test
