name: windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        yarn --link-duplicates --pure-lockfile --ignore-engines
        yarn dist
